### ISSUE TITLE
Is ouster lidar available?

### ISSUE THREAD

**Issue by LTHlidar** [Ericsii/FAST_LIO#10]
First, thank you for your FAST LIO ROS2 package.

I have a question, I am currently using ouster lidar.
To launch a package using ouster lidar, 
` ros2 launch fast_lio mapping_ouster64.launch` command into the terminal? 
Or, inside the mapping.launch.py file, modify the 'mid360.yaml'  to 'ouster64.yaml' and run the command
`ros2 launch fast_lio mapping.launch.py` and run it?

Actually, I tried both ways, but it didn't work, hence the question.

Thanks.

**Comment by Ericsii** [comment]
Other types of lidar support will be updated in recent days

**Comment by LTHlidar** [comment]
I successfully ran fast LIO2 using the Outster LiDAR topic. 

Previously, the following error occurred when running Fast lio2. 
`[laser_mapping] : New publisher discovered on topic '/ouster/imu', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY`

in laserMapping.cpp 
`sub_pcl_pc_ = this->create_subscription<sensor_msgs::msg::PointCloud2>(lid_topic, 10, standard_pcl_cbk)` 
need to be fixed to
`sub_pcl_pc_ = this->create_subscription<sensor_msgs::msg::PointCloud2>(lid_topic, rclcpp::SensorDataQoS(), standard_pcl_cbk)`

If the QOS settings of lidar publish topic and fast lio subscriber are different(ex : RELIABILITY or Best_effort), the ouster topic is not subscribed.
I haven't analyzed the data exactly, but it seems to work well with ouster lidar.

**Comment by LTHlidar** [comment]
And I don't know why, but I need to paste the code from mid360.yaml file into ouster64.yaml and replace it with the right code for ouster64.yaml, then fast lio 2 will run without error.
I'm not an expert, so I don't know the exact solution, but I'm commenting in case it helps. Thanks (I think it's probably due to the different systems the files were created on).

**Comment by Ericsii** [comment]
> And I don't know why, but I need to paste the code from mid360.yaml file into ouster64.yaml and replace it with the right code for ouster64.yaml, then fast lio 2 will run without error.

This is because I only migrated mid360.yaml to ros2, ouster and other lidars are not migrated yet.

**Comment by Ericsii** [comment]
Other lidar support is added. You can have a try.
