### ISSUE TITLE
如何保存地图文件呢

### ISSUE THREAD

**Issue by 20082896** [Ericsii/FAST_LIO#11]

**Comment by Ericsii** [comment]
调用/map_save这个service

**Comment by 20082896** [comment]
> 调用/map_save这个service

具体如何操作啊老哥，我太菜了

**Comment by Ericsii** [comment]
打开rqt->plugins->Services->Service Caller->找到map_save这个service->点击Call

**Comment by 20082896** [comment]
> 打开rqt->plugins->Services->Service Caller->找到map_save这个service->点击Call
感谢感谢，我理解错了，我以为这个服务是要改源代码才能启用的，刚才看了一下是自动启动的
感谢老哥

**Comment by YuehChuan** [comment]
@20082896 
Here

<img width="1249" height="487" alt="Image" src="https://github.com/user-attachments/assets/76265da8-909e-409e-afb9-fd68a884e753" />
