### ISSUE TITLE
How to mapping with realsense?

### ISSUE THREAD

**Issue by shengxiamo** [Ericsii/FAST_LIO#21]
I wonder whether this project support mapping with realsense d435(without build-in IMU) ?If yes,what should I do?I

**Comment by Ericsii** [comment]
FASTLIO is only for lidar-IMU. If all you have is a depth camera input then this system won't work

**Comment by shengxiamo** [comment]
Thanks. Do you plan to develop a more general version of FAST_LIO_ROS2？

**Comment by shengxiamo** [comment]
只是问问佬，没有压力的意思。或者有没有相似的，更通用的，能满足我的要求的框架推荐？

**Comment by Ericsii** [comment]
如果是使用realsense的话可以试试rtabmap这个库，官方给了很详细的使用文档
https://github.com/introlab/rtabmap

**Comment by shengxiamo** [comment]
好的，谢谢佬
