### ISSUE TITLE
Hi rosbags-convert question

### ISSUE THREAD

**Issue by SuperQueen20010701** [Ericsii/FAST_LIO#26]
您好。我目前遇到一个问题，通过利用rosbags-converter 我发现对应的bag中的/livox/lidar信息仍然是livox_ros_driver类型，导致我在程序中利用livox_ros2_driver或者livox_ros_driver2都不能正确读取点云数据。我的环境是ubuntu 22.04。
我已经将我的程序适配到了livox_ros2_driver（适配avia的版本），但是使用[https://github.com/hku-mars/FAST_LIO](url)提供的数据包，经过转换的db3数据类型仍然是livox_ros_driver,我改完程序的消息接收端口适配的是livox_interface，如下图，请问您能够提供相关的改进建议么？

**Comment by SuperQueen20010701** [comment]
![2024-11-27 14-58-27 的屏幕截图](https://github.com/user-attachments/assets/17173db5-51f8-4e19-933d-a10eccf5f6d8)

**Comment by Ericsii** [comment]
此问题是livox官方驱动对ros1和ros2不同版本支持的问题，请移步livox官方 https://github.com/Livox-SDK/livox_ros_driver

**Comment by SuperQueen20010701** [comment]
请问，您在执行rosbag到ros2 bag转换后，成功实现点云数据读取了吗？
