### ISSUE TITLE
Frame id of odometry

### ISSUE THREAD

**Issue by maxxbolotov** [Ericsii/FAST_LIO#27]
Hi again! 
I need to use the odometry data that provides fast_lio but I can’t find out what is it frame id. 
Usually the frame id of the odometry data is odom but I didn’t find any mention of this frame id in cfg and src. Also if I try to set fixed frame in RVIZ as odom it says that such frame id doesn’t exist. So I assume that it has a differ name. 
I understand that the publishing topic of odometry is /Odometry but there is no such frame id name either. 
Can you help me with understanding of this frame id name?

**Comment by Ericsii** [comment]
As the original ROS1 version, the frame_id of FAST_LIO2 is `camera_init`
