### ISSUE TITLE
fast_lio: Cannot locate rosdep definition for [rospy]

### ISSUE THREAD

**Issue by zyw722** [Ericsii/FAST_LIO#6]
hello author I have a problem when i execute 'rosdep install --from-paths src --ignore-src -y ' .Do you know how to solve it:
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
fast_lio: Cannot locate rosdep definition for [rospy]

**Comment by Ericsii** [comment]
Just ignore this error or you can just delete the line contains `rospy` in `package.xml`
