### ISSUE TITLE
can run this code in ros2 galactic?

### ISSUE THREAD

**Issue by zyw722** [Ericsii/FAST_LIO#7]

**Comment by Ericsii** [comment]
I did not test this on galactic. You can have a try

**Comment by DongFanggcz** [comment]
> I did not test this on galactic. You can have a try我没有在银河上测试过这个。你可以试试
we ran through the code on the foxy of ROS2 and made changes
https://github.com/ifr-cv/FAST_LIO/tree/f21bfedaa10029bcf14a09c8cf2e06927917c61c
