### ISSUE TITLE
Point Cloud Output "Fuzzy" and Path is not correct

### ISSUE THREAD

**Issue by ryanpdoc57** [Ericsii/FAST_LIO#9]
I am using ROS2 Foxy to run the package. Pictured below is the Velodyne bag file output in RViz for  "20120615-001", however, the same result happens no matter what LiDAR type/bag file I use. The output is extremely "fuzzy" and shows a significantly lower-quality image as the ROS1 version of the same bag file. Also, the path is not completely accurate, as seen in the images below. There is some drift in Odometry that appears in the ROS2 version, but not the ROS1 version. Does anyone have any input on this? The first Image is ROS1, while the second image is ROS2. Thanks in advance!
![ROS1](https://github.com/Ericsii/FAST_LIO/assets/74368846/a93edcd5-9b05-4481-b686-715176140dbb)
![ROS2](https://github.com/Ericsii/FAST_LIO/assets/74368846/a6798363-3198-48b8-a55e-52566bad97a9)

**Comment by Ericsii** [comment]
I did not migrate the RVIZ config from the original version. The RVIZ config is a handmade one. Due to FASTLIO being only a lidar odometry if the trajectory is correct then everything is working correctly.

You should disable the pointcloud view in RVIZ and compare only the trajectories generated from ROS1 and ROS2.

**Comment by ryanpdoc57** [comment]
As you can see in the following picture, the path is also not correct. Measuring with a protractor, the angle of the path using ROS2 (left image) is about 30 degrees, while the angle for ROS1 (right image) is about 40 degrees. The red line being flat in both images (a wall or something like that) proves the difference in the angles.  The trajectories should be the exact same. Have you done any data set testing that proves the full functionality of ROS2 FAST-LIO? Through my testing using different data sets, I have reason to believe the package does not function as expected. I would love to be wrong though. 
<img width="753" alt="ROS1 vs ROS2" src="https://github.com/Ericsii/FAST_LIO/assets/74368846/de4c46fc-8603-4170-a33f-b2f7fd62594d">

**Comment by Ericsii** [comment]
Could you please test it on some open-source datasets with ground-truth odometry? In this way, we can compare the effects of these two versions.

**Comment by ryanpdoc57** [comment]
> Could you please test it on some open-source datasets with ground-truth odometry? In this way, we can compare the effects of these two versions.

I am trying to use the M2GDR data set (https://github.com/SJTU-ViSYS/M2DGR?tab=readme-ov-file) which contains ground truth information. I am using plot juggler to plot the trajectory of the odometry from FAST-LIO, but I don't know how to overlay this plot with the ground truth (.txt file). Do you have any advice on how to do this? The bag files are too big for Matlab.

**Comment by Ericsii** [comment]
You can use [EVO](https://github.com/MichaelGrupp/evo). This is a well-used toolbox for SLAM evaluation

**Comment by Ericsii** [comment]
Close for no update

**Comment by ginwodka** [comment]
I can confirm this.
Something is different compared to original FAST LIO 2 version with ROS1. First of all, you have a spare pointcloud. It doesnt matter if i have point filter num = 1. Thats definitely not the case in ROS1. Second, i have difficulties while mapping indoor and outdoor. Most of the time the SLAM fails. And i mapped a lot of objects with Fast Lio 2 and ROS1 and there were no problems at all. So i assume this version here is not working properly :(
